"""
Django settings for breathing_bot_project project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load the .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# DEBUG = False

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your Core App Module Registered Here
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # <--- CRITICAL: Added for language translation switching
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'breathing_bot_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'breathing_bot_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGIN_REDIRECT_URL = 'core:free_breathing'
LOGIN_URL = '/'

# Internationalization (May 2026 Multilingual Support Setup)
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOCALE_INDEPENDENT_PATHS = ['/']

# over browser headers if it exists, otherwise default to 'en'.
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 31536000 # 1 year
LANGUAGE_COOKIE_HTTPONLY = True

# Explicitly define the most widely spoken global languages
LANGUAGES = [
    ('en', 'English'),         # Global lingua franca / North America / Europe / India
    ('zh-hans', 'Chinese'),   # Mandarin Chinese (Simplified script)
    ('hi', 'Hindi'),           # India (Northern / Central region support)
    ('es', 'Spanish'),         # Latin America / Spain
    ('fr', 'French'),          # West Africa / France / Canada
    ('ar', 'Arabic'),          # Middle East / North Africa
    ('bn', 'Bengali'),         # West Bengal / Bangladesh
    ('pt', 'Portuguese'),      # Brazil / Portugal
    ('ru', 'Russian'),         # Eastern Europe / Central Asia
    ('ur', 'Urdu'),            # Pakistan / India
    ('id', 'Indonesian'),      # Southeast Asia
    ('de', 'German'),          # Central Europe
    ('ja', 'Japanese'),        # East Asia
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('kn', 'Kannada'),
    ('ml', 'Malayalam'),
    ('gu', 'Gujarati'),
    ('mr', 'Marathi'),
    ('as', 'Assamese'),
    ('sv', 'Swedish'),
    ('ko', 'Korean'),
    ('vi', 'Vietnamese'),
    ('he', 'Hebrew'),
]

# Path where your .po and .mo translation catalogs will be generated
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images, Web Audio Assets)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Update this to match your app's actual directory layout
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend — use console during dev, swap for SMTP in production
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production, replace with:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your@email.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
# DEFAULT_FROM_EMAIL = 'Breathing Bot <your@email.com>'

# At the bottom of settings.py
