"""
Django settings for breathing_bot_project project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""
import os
import dj_database_url
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Load the .env file (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── PRODUCTION & SECURITY SETTINGS ───────────────────────────────────────────

def get_env_variable(var_name):
    """Ensure environment variables are strictly defined; otherwise, crash cleanly."""
    try:
        return os.environ[var_name]
    except KeyError:
        error_msg = f"The required environment variable '{var_name}' is missing."
        raise ImproperlyConfigured(error_msg)

# Strictly pulled from environment. No sloppy fallbacks.
SECRET_KEY = get_env_variable('SECRET_KEY')

# Evaluates explicitly to True only if explicitly set to 'True'
DEBUG = False

# Allow local environments and any subdomains on Render
ALLOWED_HOSTS = [
    'breathing-bot.onrender.com',
    '127.0.0.1',
    'localhost',
]

# Render specific proxy header rule
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── ADDITIONAL SECURITY HARDENING ────────────────────────────────────────────
if not DEBUG:
    # Redirect all HTTP traffic to HTTPS (Fixes W008)
    SECURE_SSL_REDIRECT = True

    # Secure Cookies: Session and CSRF only over HTTPS (Fixes W012 & W016)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Guard against XSS attacks and content type guessing
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # HTTP Strict Transport Security (HSTS) (Fixes W004)
    SECURE_HSTS_SECONDS = 3600  # 1 hour for safety verification initially
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ── APPLICATION DEFINITION ───────────────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your Core App Module Registered Here
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- CRITICAL: Added for production static/audio asset rendering
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # <--- CRITICAL: Added for language translation switching
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'breathing_bot_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'breathing_bot_project.wsgi.application'


# ── DATABASE CONFIGURATION ───────────────────────────────────────────────────
if not DEBUG or os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ── PASSWORD VALIDATION ──────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = 'core:free_breathing'
LOGIN_URL = '/'


# ── INTERNATIONALIZATION ─────────────────────────────────────────────────────
LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

LOCALE_INDEPENDENT_PATHS = ['/']

LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 31536000 # 1 year
LANGUAGE_COOKIE_HTTPONLY = True

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
    ('as', 'Assamese'),
    ('bn', 'Bengali'),
    ('zh-hans', 'Chinese'),
    ('fr', 'French'),
    ('de', 'German'),
    ('gu', 'Gujarati'),
    ('he', 'Hebrew'),
    ('hi', 'Hindi'),
    ('id', 'Indonesian'),
    ('it', 'Italian'),
    ('ja', 'Japanese'),
    ('kn', 'Kannada'),
    ('ko', 'Korean'),
    ('ml', 'Malayalam'),
    ('mr', 'Marathi'),
    ('pt', 'Portuguese'),
    ('ru', 'Russian'),
    ('es', 'Spanish'),
    ('sv', 'Swedish'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('ur', 'Urdu'),
    ('vi', 'Vietnamese'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# ── STATIC FILES (CSS, JAVASCRIPT, AUDIO ASSETS) ─────────────────────────────
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

# Destination directory where all static files get compiled for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Storage Engine optimizations: compresses files and aggressively caches files safely
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# ── MISCELLANEOUS DEFINITIONS ────────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend infrastructure setup
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = f"Breathing Bot <{os.environ.get('EMAIL_HOST_USER')}>"