"""
Django settings for breathing_bot_project project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Load the .env file (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── PRODUCTION & SECURITY SETTINGS ───────────────────────────────────────────
# Read from environment variables, use fallbacks for local dev
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-development-fallback-key-12345')

# Automatically turns off debug mode on Render if DJANGO_DEBUG=False is set in dashboard
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Allow local environments and any subdomains on Render
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.onrender.com']


# ── APPLICATION DEFINITION ───────────────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your Core App Module Registered Here
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- CRITICAL: Added for production static/audio asset rendering
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # <--- CRITICAL: Added for language translation switching
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'breathing_bot_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'breathing_bot_project.wsgi.application'


# ── DATABASE CONFIGURATION ───────────────────────────────────────────────────
# If we are in production on Render, pull the managed PostgreSQL connection
if not DEBUG:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600
        )
    }
else:
    # Local Development Database (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ── PASSWORD VALIDATION ──────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = 'core:free_breathing'
LOGIN_URL = '/'


# ── INTERNATIONALIZATION ─────────────────────────────────────────────────────
LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

LOCALE_INDEPENDENT_PATHS = ['/']

LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 31536000 # 1 year
LANGUAGE_COOKIE_HTTPONLY = True

LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', 'Chinese'),
    ('hi', 'Hindi'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('ar', 'Arabic'),
    ('bn', 'Bengali'),
    ('pt', 'Portuguese'),
    ('ru', 'Russian'),
    ('ur', 'Urdu'),
    ('id', 'Indonesian'),
    ('de', 'German'),
    ('ja', 'Japanese'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('kn', 'Kannada'),
    ('ml', 'Malayalam'),
    ('gu', 'Gujarati'),
    ('mr', 'Marathi'),
    ('as', 'Assamese'),
    ('sv', 'Swedish'),
    ('ko', 'Korean'),
    ('vi', 'Vietnamese'),
    ('he', 'Hebrew'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# ── STATIC FILES (CSS, JAVASCRIPT, AUDIO ASSETS) ─────────────────────────────
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

# Destination directory where all static files get compiled for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Storage Engine optimizations: compresses files and aggressively caches files safely
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ── MISCELLANEOUS DEFINITIONS ────────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend infrastructure setup
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = f"Breathing Bot <{os.environ.get('EMAIL_HOST_USER')}>"