# Generated by Django 6.0.5 on 2026-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
