# Generated by Django 6.0.5 on 2026-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="breathingsession",
            name="minutes_meditated",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
